# Generated by Django 4.2.4 on 2023-08-25 19:55

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('transcript', ckeditor.fields.RichTextField()),
                ('youtube_url', models.CharField(max_length=252)),
                ('apple_url', models.CharField(max_length=252)),
                ('spotify_url', models.CharField(max_length=252)),
                ('thumbnail_url', models.CharField(max_length=252)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('sequence_number',)},
            },
        ),
    ]
