# Generated by Django 4.2.4 on 2023-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='apple_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
