# Generated by Django 4.2.4 on 2023-08-25 20:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_podcast_apple_url_alter_podcast_spotify_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='transcript',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
