# Generated by Django 4.2.4 on 2023-08-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_podcast_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='podcast',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='podcast/thumbnail/'),
        ),
    ]
