# Generated by Django 4.2.4 on 2023-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_remove_podcast_thumbnail_url_podcast_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
