# Generated by Django 4.2.4 on 2023-08-27 22:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_alter_podcast_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='transcript',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
