# Generated by Django 4.2.4 on 2023-08-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_dashboardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='join_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
