# Generated by Django 4.2.4 on 2023-08-28 11:50

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_dashboardmodel_join_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='archive/profile/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='archive/thumbnail/')),
                ('content', ckeditor.fields.RichTextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='archives', to='podcast.archivetags')),
            ],
        ),
    ]
