# Generated by Django 4.2.4 on 2023-08-22 08:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('transcript', models.TextField()),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('apple_url', models.URLField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('sequence_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.book')),
                ('next_chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.bookchapter')),
            ],
            options={
                'unique_together': {('book', 'sequence_number')},
            },
        ),
    ]
