# Generated by Django 4.2.4 on 2023-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='sequence_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
