# Generated by Django 4.2.4 on 2023-08-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_bookchapter_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='category_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
