# Generated by Django 4.2.4 on 2023-08-24 17:17

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_bookchapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
    ]
