# Generated by Django 4.2.4 on 2023-08-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_book_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
